version: '2'
services:
  app:
    build: .
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/function/node_modules
    ports:
      - '3000:3000'
    command: 'node index.js'